In [20]:
# Numpy - numeric python
import numpy as np

# arrays

p = np.array([1,2,3,4])

print(p.dtype) # data type of the members of this structure
type(p) # data type of this array

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]]) # looks like a matrix

b[-1]

# array adjustments
c = np.array([[1,2,3],
              [4,5,6]])
print (c.reshape(3,2))

# transform
print(c.T)

# dot
print(np.dot(c,c.T))

int32
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [89]:
# random numbers
np.random.seed(20)
print(np.random.randint(5))

# arange

r = np.arange(10)
np.random.shuffle(r)
print(r)

3
[7 1 8 5 0 2 6 3 4 9]


In [99]:
# saving and loading data
np.save('my_numpy_structure.npy', r )
np.savetxt('my_numpy_structure.txt', r, delimiter=',' )

d = np.loadtxt('my_numpy_structure.txt')

print(d)


[7. 1. 8. 5. 0. 2. 6. 3. 4. 9.]


In [102]:
# linear algebra
l = np.array([[1,4,6],
              [5,2,2],
              [-1,6,8]])

w, v = np.linalg.eig(l)
print (w,v)

n = np.array([[1],[2],[3]])

x = np.linalg.solve(l,n)
x

[-0.1111635 +1.57564872j -0.1111635 -1.57564872j 11.22232699+0.j        ] [[-0.09815679+0.27262295j -0.09815679-0.27262295j  0.57642041+0.j        ]
 [ 0.76830893+0.j          0.76830893-0.j          0.45911115+0.j        ]
 [-0.56562092-0.07626488j -0.56562092+0.07626488j  0.67598555+0.j        ]]


array([[-1.77635684e-16],
       [ 2.50000000e+00],
       [-1.50000000e+00]])